//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.29 at 03:47:32 PM IST 
//


package com.gov.Authmis.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


@XmlRootElement(name = "AuthRequest")
public class Authrequest {

    
    
    protected String uuid;
    
    protected String flagType;
    
    protected String subaua;
    
    protected String ver;
    
    @XmlAttribute(name = "uuid")
	public String getUuid() {
		return uuid;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	
	@XmlAttribute(name = "flagType")
	public String getFlagType() {
		return flagType;
	}
	public void setFlagType(String flagType) {
		this.flagType = flagType;
	}
	
	@XmlAttribute(name = "subaua")
	public String getSubaua() {
		return subaua;
	}
	public void setSubaua(String subaua) {
		this.subaua = subaua;
	}
	
	@XmlAttribute(name = "ver")
	public String getVer() {
		return ver;
	}
	public void setVer(String ver) {
		this.ver = ver;
	}
    

}